Settings:
  #SQLite MySQL
  storage-type: MySQL
  #Whether to save data asynchronously(SQLite does not support)
  #Query data, creating data has nothing to do with this option
  async: true
  #use connection pool or not
  usepool: false


#SQLite settings
SQLite:
  #Address is the folder path
  path: Default


#MySQL settings
MySQL:
  host: sql5.freemysqlhosting.net
  port: 3306
  user: sql5461032
  pass: agmrbc6XbK
  database: sql5461032
  #auto add "_", can use %sign% to indicate Server ID (BungeeCord settings)
  table-suffix: ''
  property:
    usessl: false
    encoding: utf8
    timezone: ''
    allowPublicKeyRetrieval: false


#Connection pool settings
Pool-Settings:
  maximum-pool-size: 10
  minimum-idle: 10
  maximum-lifetime: 180000
  idle-timeout: 60000