
[general]
	#Enable/Disable Serverside Overrides
	enabled = true
	#Internal Version Number. NO TOUCHY!
	version = 1

#The Multi Player Event
[multi_player]
	#Enable/Disable the Multi Player Event
	enabled = true
	#The first line of text under the app name
	description = "Playing on Lightning-MC.xyz with %players% players"
	#The second line of text under the app name
	state = "Playing online"
	#The Asset ID of the image to display as the large image
	largeImageKey = "lightning_pixelmon"
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's J.T.'s Modded Pixelmon!"
	#The Asset ID of the image to display as the small image
	smallImageKey = "pokeball"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	#The buttons to display on Discord
	buttons = []

#World/Dimension Image Overrides
[world_images]
	#Enabled/Disable custom images for Worlds/Biomes
	enabled = true
	#The Worlds/Biomes to override
	worlds = []

